INFO:root:
 NEW RUN STARTING: 2021.10.18 17:56
INFO:root:Database has been created at c:\Coding\Amazon Orders Parser\Helper Files\orders.db
DEBUG:root:Before inserting new orders, orders table contains 0 entries associated with AmazonEU channel
INFO:root:Returning 346/346 new/loaded orders for further processing
INFO:root:Loaded txt contains: 346. Further processing: 346 orders
INFO:root:
---- Parsing with sqlite + ParseOrders done. SQLAlchemy turn + ParseOrders
WARNING:root:Tried deleting file: c:\Coding\Amazon Orders Parser\Helper Files\AmazonEU-LP.csv, but apparently human has taken care of it first. (File not found)
WARNING:root:Tried deleting file: c:\Coding\Amazon Orders Parser\Helper Files\AmazonEU-LP-Tracked.csv, but apparently human has taken care of it first. (File not found)
INFO:root:Sorting orders by shippment company specific to Amazon AmazonEU ruleset
INFO:root:TESTING FLAG IS: True. Refer to test_exports in parse_orders.py
INFO:root:Same Buyer Orders have been written to c:\Coding\Amazon Orders Parser\AmazonEU-Same Buyer 2021.10.18 17.56.txt and being showed to client
DEBUG:root:FILE EXPORTS SUSPENDED. TESTING ADDING TO DATABSE ONLY
DEBUG:root:This is backup path being saved to program_run fpath column: C:\Coding\Ebay\Working\Backups\Amazon exports\Collected exports\export 2021.04.29 EU.txt
DEBUG:root:Added new run: <ProgramRun id: 1, sales_channel: AmazonEU, timestamp: 2021-10-18 17:56:24.884969, fpath: C:\Coding\Ebay\Working\Backups\Amazon exports\Collected exports\export 2021.04.29 EU.txt>, created backup
DEBUG:root:New orders added, flushing old records complete, backup after created at: c:\Coding\Amazon Orders Parser\Helper Files\orders_lrun.db
INFO:root:Total of 346 new orders have been added to database, after exports were completed
INFO:root:
RUN ENDED: 2021.10.18 17:56

INFO:root:
 NEW RUN STARTING: 2021.10.18 18:12
INFO:root:Database has been created at c:\Coding\Amazon Orders Parser\Helper Files\orders.db
DEBUG:root:Backup for orders_b4lrun.db suspended due to testing: True
DEBUG:root:Before inserting new orders, orders table contains 0 entries associated with AmazonEU channel
INFO:root:Returning 346/346 new/loaded orders for further processing
INFO:root:Loaded txt contains: 346. Further processing: 346 orders
WARNING:root:Tried deleting file: c:\Coding\Amazon Orders Parser\Helper Files\AmazonEU-LP.csv, but apparently human has taken care of it first. (File not found)
WARNING:root:Tried deleting file: c:\Coding\Amazon Orders Parser\Helper Files\AmazonEU-LP-Tracked.csv, but apparently human has taken care of it first. (File not found)
INFO:root:Sorting orders by shippment company specific to Amazon AmazonEU ruleset
INFO:root:TESTING FLAG IS: True. Refer to test_exports in parse_orders.py
DEBUG:root:FILE EXPORTS SUSPENDED. TESTING ADDING TO DATABSE ONLY
DEBUG:root:This is backup path being saved to program_run fpath column: C:\Coding\Ebay\Working\Backups\Amazon exports\Collected exports\export 2021.04.29 EU.txt
DEBUG:root:Added new run: <ProgramRun id: 1, sales_channel: AmazonEU, timestamp: 2021-10-18 18:12:23.611805, fpath: C:\Coding\Ebay\Working\Backups\Amazon exports\Collected exports\export 2021.04.29 EU.txt>, created backup
DEBUG:root:Backup for orders_lrun.db suspended due to testing: True
DEBUG:root:New orders added, flushing old records complete, backup after created at: c:\Coding\Amazon Orders Parser\Helper Files\orders_lrun.db
INFO:root:Total of 346 new orders have been added to database, after exports were completed
INFO:root:
RUN ENDED: 2021.10.18 18:12

